language: objective-c
osx_image: xcode9.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - bundle install
script:
  - xcodebuild -project VolumeBar/VolumeBar.xcodeproj -scheme VolumeBar -sdk iphonesimulator11.2 build analyze
  - bundle exec pod lib lint --verbose
  